# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newBackground.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import QLabel, QLineEdit, QPushButton


class Ui_NewBackground(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 273)
        self.label = QLabel(Form)
        self.label.setGeometry(QRect(80, 40, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QLabel(Form)
        self.label_2.setGeometry(QRect(80, 90, 51, 21))
        self.label_2.setObjectName("label_2")
        self.width_ledit = QLineEdit(Form)
        self.width_ledit.setGeometry(QRect(140, 40, 113, 21))
        self.width_ledit.setObjectName("width_ledit")
        self.height_ledit = QLineEdit(Form)
        self.height_ledit.setGeometry(QRect(140, 90, 113, 21))
        self.height_ledit.setObjectName("height_ledit")
        self.label_3 = QLabel(Form)
        self.label_3.setGeometry(QRect(270, 40, 72, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QLabel(Form)
        self.label_4.setGeometry(QRect(270, 90, 72, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QLabel(Form)
        self.label_5.setGeometry(QRect(80, 140, 61, 31))
        self.label_5.setObjectName("label_5")
        self.select_white_label = QLabel(Form)
        self.select_white_label.setGeometry(QRect(150, 140, 50, 50))
        self.select_white_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:3px;\n"
"border-style:solid;\n"
"border-color: rgb(176, 176, 176);\n"
"border-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.select_white_label.setText("")
        self.select_white_label.setObjectName("select_white_label")
        self.label_7 = QLabel(Form)
        self.label_7.setGeometry(QRect(200, 150, 50, 50))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.select_transparen_label = QLabel(Form)
        self.select_transparen_label.setGeometry(QRect(220, 140, 50, 50))
        self.select_transparen_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/pic/images/transparent-bg.png);\n"
"border-width:3px;\n"
"border-style:solid;\n"
"border-color: rgb(176, 176, 176);\n"
"border-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.select_transparen_label.setText("")
        self.select_transparen_label.setObjectName("select_transparen_label")
        self.define_color_label = QLabel(Form)
        self.define_color_label.setGeometry(QRect(290, 140, 50, 50))
        self.define_color_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"border-width:3px;\n"
"border-style:solid;\n"
"border-color: rgb(176, 176, 176);\n"
"border-radius:10px;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.define_color_label.setText("")
        self.define_color_label.setObjectName("define_color_label")
        self.label_10 = QLabel(Form)
        self.label_10.setGeometry(QRect(160, 200, 31, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QLabel(Form)
        self.label_11.setGeometry(QRect(230, 200, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QLabel(Form)
        self.label_12.setGeometry(QRect(280, 200, 81, 16))
        self.label_12.setObjectName("label_12")
        self.ensure_bg_button = QPushButton(Form)
        self.ensure_bg_button.setGeometry(QRect(100, 230, 93, 28))
        self.ensure_bg_button.setObjectName("ensure_bg_button")
        self.cancel_bg_button = QPushButton(Form)
        self.cancel_bg_button.setGeometry(QRect(240, 230, 93, 28))
        self.cancel_bg_button.setObjectName("cancel_bg_button")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "新建背景"))
        self.label.setText(_translate("Form", "宽度："))
        self.label_2.setText(_translate("Form", "高度："))
        self.width_ledit.setText(_translate("Form", "270"))
        self.height_ledit.setText(_translate("Form", "270"))
        self.label_3.setText(_translate("Form", "像素"))
        self.label_4.setText(_translate("Form", "像素"))
        self.label_5.setText(_translate("Form", "背景色："))
        self.label_10.setText(_translate("Form", "白色"))
        self.label_11.setText(_translate("Form", "透明"))
        self.label_12.setText(_translate("Form", "自定义颜色"))
        self.ensure_bg_button.setText(_translate("Form", "确定"))
        self.cancel_bg_button.setText(_translate("Form", "取消"))
import resources_rc
