# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'repeat_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import QProgressBar, QLabel


class Ui_show_repeat_progress_form(object):
    def setupUi(self, show_repeat_progress_form):
        show_repeat_progress_form.setObjectName("show_repeat_progress_form")
        show_repeat_progress_form.resize(607, 83)
        self.show_repeat_progressbar = QProgressBar(show_repeat_progress_form)
        self.show_repeat_progressbar.setGeometry(QRect(20, 20, 591, 23))
        self.show_repeat_progressbar.setProperty("value", 0)
        self.show_repeat_progressbar.setObjectName("show_repeat_progressbar")
        self.show_repeat_name_label = QLabel(show_repeat_progress_form)
        self.show_repeat_name_label.setGeometry(QRect(20, 50, 551, 21))
        self.show_repeat_name_label.setText("")
        self.show_repeat_name_label.setObjectName("show_repeat_name_label")

        self.retranslateUi(show_repeat_progress_form)
        QMetaObject.connectSlotsByName(show_repeat_progress_form)

    def retranslateUi(self, show_repeat_progress_form):
        _translate = QCoreApplication.translate
        show_repeat_progress_form.setWindowTitle(_translate("show_repeat_progress_form", "多打进度"))
